# -*- coding: utf-8 -*-
"""maquina_do_tempo_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cS4N3pEpw4Y6kC9Bv51Me7D-fhq6sFTK

Instalando google-generativeai
"""

pip install -q -U google-generativeai

"""Importanto o SDK"""

import google.generativeai as genai

GOOGLE_API_KEY = 'COLE_A_API_AQUI'
genai.configure(api_key=GOOGLE_API_KEY)

"""Listando modelos"""

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print (m.name)

"""Configuração do modelo"""

generation_config = {
    "candidate_count": 1,
    "temperature": 0.8,

}

"""Segurança do modelo"""

safety_settings = {
    "HARASSMENT": "BLOCK_LOW_AND_ABOVE",
    "HATE": "BLOCK_LOW_AND_ABOVE",
    "SEXUAL": "BLOCK_LOW_AND_ABOVE",
    "DANGEROUS": "BLOCK_LOW_AND_ABOVE",
}

"""Inicializando o modelo"""

model = genai.GenerativeModel(model_name="gemini-1.0-pro",
                              generation_config = generation_config,
                              safety_settings = safety_settings)

chat = model.start_chat(history=[])

from IPython.display import Markdown

markdown_text = """
**Chronos:** Saudações, viajante do tempo! Eu sou Chronos, seu guia pelas areias do tempo. Prepare-se para embarcar em uma jornada extraordinária para eras passadas, onde você encontrará mentes brilhantes e almas lendárias.

**Chronos:** Diga-me, viajante, com qual dessas figuras históricas você deseja conversar?

**Opções de Personagens:**


**A)** Moisés: O profeta do Antigo Testamento, líder do Êxodo e portador dos Dez Mandamentos. Prepare-se para discussões sobre ética, religião e a natureza humana.

**B)** Cleópatra: A última faraó do Egito, conhecida por sua beleza, inteligência e astúcia política. Mergulhe nas maravilhas do Egito Antigo e aprenda sobre poder, amor e intriga.

**C)** Leonardo da Vinci: O gênio multifacetado do Renascimento, mestre da arte, ciência e invenção. Prepare-se para ser inspirado por sua criatividade ilimitada e suas ideias visionárias.

**D)** Albert Einstein: O físico revolucionário do século XX, cuja Teoria da Relatividade mudou nossa compreensão do espaço, tempo e gravidade. Prepare-se para expandir sua mente e mergulhar nos mistérios do universo.

**Chronos:** Então, quem será? Escolha com sabedoria, pois cada encontro será uma experiência única e inesquecível!
"""
Markdown(markdown_text)

"""Selecionando a opção"""

opcao_inicio = input('Selecione uma das opção desejada A: Moises / B: Cleópatra / C: Leonardo da Vinci / D: Albert Einstein (Usar letra Maiuscula):')

if opcao_inicio == "A":
    response_a_presentation = chat.send_message("\n\nFaça uma breve apresentação Moisés do antigo testamento na primeira pessoas, como se o próprio Moises estivese falando")
    resposta_inicia_a = print(response_a_presentation.text)
    print('\n\n O que você deseja saber? \n A) Os Dez Mandamento \n B) O Êxodo \n C) A Sarça Ardente \n D) O Monte Sinai \n E) Sair \n\n')
    opcao_intro_personagem = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem == "A":
        response_intro_personagem_a = chat.send_message("\n\nFaça um resumo sobre os 10 mandamentos na primeira pessoas, como se o próprio Moises estivese falando. Não usar esse texto **Que a paz do Senhor esteja com todos vocês.**")
        resposta_intro_personagem_a = print(response_intro_personagem_a.text)
        print('\n\n Selecione outra opção: \n B) O Êxodo \n C) A Sarça Ardente \n D) O Monte Sinai \n E) Sair \n\n')
        opcao_intro_personagem = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem == "B":
        response_intro_personagem_b = chat.send_message("\n\nFaça um resumo sobre o êxodo do povo judeu do egito na primeira pessoas, como se o próprio Moises estivese falando.  Não usar esse texto **Que a paz do Senhor esteja com todos vocês.**")
        resposta_intro_personagem_b = print(response_intro_personagem_b.text)
        print('\n\n Selecione outra opção: \n C) A Sarça Ardente \n D) O Monte Sinai \n E) Sair \n\n')
        opcao_intro_personagem = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem == "C":
            response_intro_personagem_c = chat.send_message("\n\nFaça um resumo sobre a sarça ardente na primeira pessoas, como se o próprio Moises estivese falando. Não usar esse texto **Que a paz do Senhor esteja com todos vocês.**")
            resposta_intro_personagem_c = print(response_intro_personagem_c.text)
            print('\n\n Selecione outra opção: \n D) O Monte Sinai \n E) Sair \n\n')
            opcao_intro_personagem = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem == "D":
              response_intro_personagem_d = chat.send_message("\n\nFaça um resumo sobre o monte sinai, como se o próprio Moises estivese falando. Não usar esse texto **Que a paz do Senhor esteja com todos vocês.**")
              resposta_intro_personagem_d = print(response_intro_personagem_d.text)
              print('\n\n Selecione outra opção: \n E) Sair \n\n')
              opcao_intro_personagem = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem == "E":
                response_intro_personagem_e = chat.send_message("\n\Faça uma despedida e um breve agradecimento de uma conversa com uma pessoa, como se o próprio Moises estivese falando. Não usar esse texto **Que a paz do Senhor esteja com todos vocês.**")
                resposta_intro_personagem_e = print(response_intro_personagem_e.text)
if opcao_inicio == "B":
    response_b_presentation = chat.send_message("\n\nFaça uma breve apresentação da Cleóprata com sarcasmo e inteligência, em primeira pessoas, como se a própria Cleóprata estivese falando")
    resposta_inicia_b = print(response_b_presentation.text)
    print('\n\n O que você deseja saber? \n A) Ascensão ao Trono \n B) Diplomacia e Alianças \n C) Guerras e Conflitos \n D) Origens e Família \n E) Sair \n\n')
    opcao_intro_personagem_b = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_b == "A":
        response_intro_b_personagem_a = chat.send_message("\n\nFaça um resumo sobre a Ascensão ao Trono na primeira pessoa, como se a própria cleópatra estivesse falando.")
        resposta_intro_b_personagem_a = print(response_intro_b_personagem_a.text)
        print('\n\n Selecione outra opção: \n B) Diplomacia e Alianças \n C) Guerras e Conflitos \n D) Origens e Família \n E) Sair \n\n')
        opcao_intro_personagem_b = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_b == "B":
        response_intro_b_personagem_b = chat.send_message("\n\nFaça um resumo sobre Diplomacia e Alianças na primeira pessoas, como se a própria cleópatra estivesse falando. ")
        resposta_intro_b_personagem_b = print(response_intro_b_personagem_b.text)
        print('\n\n Selecione outra opção: \n C) Guerras e Conflitos \n D) Origens e Família \n E) Sair \n\n')
        opcao_intro_personagem_b = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_b == "C":
            response_intro_b_personagem_c = chat.send_message("\n\nFaça um resumo sobre Guerras e Conflitos na primeira pessoas, como se a própria cleópatra estivesse falando.")
            resposta_intro_b_personagem_c = print(response_intro_b_personagem_c.text)
            print('\n\n Selecione outra opção: \n D) Origens e Família \n E) Sair \n\n')
            opcao_intro_personagem_b = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_b == "D":
              response_intro_b_personagem_d = chat.send_message("\n\nFaça um resumo sobre Origens e Família, como se a própria cleópatra estivesse falando.")
              resposta_intro_b_personagem_d = print(response_intro_b_personagem_d.text)
              print('\n\n Selecione outra opção: \n E) Sair \n\n')
              opcao_intro_personagem_b = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_b == "E":
                response_intro_b_personagem_e = chat.send_message("\n\Faça uma despedida e um breve agradecimento de uma conversa com uma pessoa, como se a própria cleópatra estivesse falando.")
                resposta_intro_b_personagem_e = print(response_intro_b_personagem_e.text)
if opcao_inicio == "C":
    response_c_presentation = chat.send_message("\n\nFaça uma breve apresentação de Leonardo da Vinci: O gênio multifacetado do Renascimento, mestre da arte, ciência e invenção. Prepare-se para ser inspirado por sua criatividade ilimitada e suas ideias visionárias, em primeira pessoa, como se o próprio Leonardo da Vinci estivese falando")
    resposta_inicia_c = print(response_c_presentation.text)
    print('\n\n O que você deseja saber? \n A) Monalisa \n B) Invenções \n C) Mistérios \n D) Renascimento  \n E) Sair \n\n')
    opcao_intro_personagem_c = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_c == "A":
        response_intro_c_personagem_a = chat.send_message("\n\nFaça um resumo sobre a Monalisa na primeira pessoa, como se o próprio Leonardo da Vinci estivese falando.")
        resposta_intro_personagem_a = print(response_intro_c_personagem_a.text)
        print('\n\n Selecione outra opção: \n B) Invenções \n C) Mistérios \n D) Renascimento  \n E) Sair \n\n')
        opcao_intro_personagem_c = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_c == "B":
        response_intro_c_personagem_b = chat.send_message("\n\nFaça um resumo sobre Invenções na primeira pessoas, como se o próprio Leonardo da Vinci estivese falando. ")
        resposta_intro_personagem_b = print(response_intro_c_personagem_b.text)
        print('\n\n Selecione outra opção: \n C) Mistérios \n D) Renascimento  \n E) Sair \n\n')
        opcao_intro_personagem_c = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_c == "C":
            response_intro_c_personagem_c = chat.send_message("\n\nFaça um resumo sobre Mistérios na primeira pessoas, como se o próprio Leonardo da Vinci estivese falando.")
            resposta_intro_personagem_c = print(response_intro_c_personagem_c.text)
            print('\n\n Selecione outra opção: \n D) Renascimento  \n E) Sair \n\n')
            opcao_intro_personagem_c = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_c == "D":
              response_intro_c_personagem_d = chat.send_message("\n\nFaça um resumo sobre Renascimento , como se o próprio Leonardo da Vinci estivese falando.")
              resposta_intro_personagem_d = print(response_intro_c_personagem_d.text)
              print('\n\n Selecione outra opção: \n E) Sair \n\n')
              opcao_intro_personagem_c = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_c == "E":
                response_intro_c_personagem_e = chat.send_message("\n\Faça uma despedida e um breve agradecimento de uma conversa com uma pessoa, como se o próprio Leonardo da Vinci estivese falando.")
                resposta_intro_personagem_e = print(response_intro_c_personagem_e.text)
if opcao_inicio == "D":
    response_d_presentation = chat.send_message("\n\nFaça uma breve apresentação de Albert Einstein: O físico revolucionário do século XX, cuja Teoria da Relatividade mudou nossa compreensão do espaço, tempo e gravidade. Prepare-se para expandir sua mente e mergulhar nos mistérios do universo, em primeira pessoa, como se o próprio Albert Einstein estivese falando")
    resposta_inicia_d = print(response_d_presentation.text)
    print('\n\n O que você deseja saber? \n A) Teoria da Relatividade \n B) O cérebro de Einstein \n C) Personalidade e hobbies \n D) Fama e reconhecimento  \n E) Sair \n\n')
    opcao_intro_personagem_d = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_d == "A":
        response_intro_d_personagem_a = chat.send_message("\n\nFaça um resumo sobre a Teoria da Relatividade na primeira pessoa, como se o próprio Albert Einstein estivese falando.")
        resposta_intro_personagem_a = print(response_intro_d_personagem_a.text)
        print('\n\n Selecione outra opção: \n B) O cérebro de Einstein \n C) Personalidade e hobbies \n D) Fama e reconhecimento  \n E) Sair \n\n')
        opcao_intro_personagem_d = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_d == "B":
        response_intro_d_personagem_b = chat.send_message("\n\nFaça um resumo sobre O cérebro de Einstein na primeira pessoas, como se o próprio Albert Einstein estivese falando. ")
        resposta_intro_personagem_b = print(response_intro_d_personagem_b.text)
        print('\n\n Selecione outra opção: \n C) Personalidade e hobbies \n D) Fama e reconhecimento  \n E) Sair \n\n')
        opcao_intro_personagem_d = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_d == "C":
            response_intro_d_personagem_c = chat.send_message("\n\nFaça um resumo sobre Personalidade e hobbies na primeira pessoas, como se o próprio Albert Einstein estivese falando.")
            resposta_intro_personagem_c = print(response_intro_d_personagem_c.text)
            print('\n\n Selecione outra opção: \n D) Fama e reconhecimento  \n E) Sair \n\n')
            opcao_intro_personagem_d = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_d == "D":
              response_intro_d_personagem_d = chat.send_message("\n\nFaça um resumo sobre Fama e reconhecimento , como se o próprio Albert Einstein estivese falando.")
              resposta_intro_personagem_d = print(response_intro_d_personagem_d.text)
              print('\n\n Selecione outra opção: \n E) Sair \n\n')
              opcao_intro_personagem_d = input('Selecione a das opção desejada (Usar letra Maiuscula):')
    if opcao_intro_personagem_d == "E":
                response_intro_d_personagem_e = chat.send_message("\n\Faça uma despedida e um breve agradecimento de uma conversa com uma pessoa, como se o próprio Albert Einstein estivese falando.")
                resposta_intro_personagem_e = print(response_intro_d_personagem_e.text)